# syntax=docker/dockerfile:1

# ---------------------------------------------------------------------------
# Suspicious Photo Detection (SPD) - multi-stage production image.
#
# Best practices applied (dockerfile-optimization skill):
#   * Base pinned to exact patch version (no moving tags).
#   * Multi-stage: build toolchain never reaches the runtime image.
#   * Dependency manifest copied before source for layer-cache hits.
#   * Non-root user with fixed numeric UID/GID.
#   * No secrets or environment-specific config baked into the image.
#   * The batch pipeline runs via the `spd` entrypoint (no long-lived server),
#     so no HEALTHCHECK is defined - there is no process to poll.
#
# Dependencies: the container installs from `requirements-docker.txt`, a
# CPU-only lockfile (torch 2.14.0+cpu / torchvision 0.29.0+cpu) generated by
# `uv pip compile requirements-docker.in`. The pipeline runs batch inference
# on CPU (`device: cpu`), so this keeps the image lean (~1.5 GB) instead of
# pulling the multi-GB CUDA wheels that the PyPI default torch build drags in.
# Embedding output is identical (same weights, same ops).
# ---------------------------------------------------------------------------

FROM python:3.13.2-slim-bookworm AS builder

ENV PIP_NO_CACHE_DIR=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1

WORKDIR /build

COPY requirements-docker.txt .

RUN pip install --prefix=/install -r requirements-docker.txt

COPY pyproject.toml .
COPY src ./src

# Install the project itself (console script `spd` + top-level packages) without
# re-resolving deps: everything is already in the /install prefix.
RUN pip install --prefix=/install --no-deps .

# ---------------------------------------------------------------------------
FROM python:3.13.2-slim-bookworm AS runtime

LABEL org.opencontainers.image.title="suspicious-photo-detection" \
      org.opencontainers.image.description="Batch ML pipeline that flags visually inconsistent outlet verification images" \
      org.opencontainers.image.source="https://github.com/Mushfiqur-Rahman-Robin/suspicious-photo-detection"

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

# Dedicated non-root user with fixed numeric IDs.
RUN groupadd --gid 10001 appgroup \
    && useradd --uid 10001 --gid appgroup --shell /usr/sbin/nologin --create-home appuser

COPY --from=builder /install /usr/local

WORKDIR /app

# Pre-create the writable directories the pipeline mounts volumes onto, owned by
# the runtime user so bind mounts behave regardless of who owns them on the host
# (see docker-compose.yml for the one-time host prep of bind-mounted dirs).
RUN mkdir -p /app/results /app/cache /app/logs \
    && chown -R appuser:appgroup /app/results /app/cache /app/logs

USER appuser

# `spd` is installed as a console script (pyproject [project.scripts]).
ENTRYPOINT ["spd"]
CMD ["--help"]